export const COLLECTIONS = {
  BRANDS: 'saiBrands',
  MARKETS: 'saiMarkets',
  PIECE_ITEMS: 'saiPieceItems',
  PIPELINE_JOBS: 'saiPipelineJobs',
  SCHEMES: 'saiSchemes',
  SCHEME_ITEMS: 'saiSchemeItems',
  USERS: 'saiUsers',
  USER_SAVED_SCHEMES: 'saiUserSavedSchemes',
  WARDROBE_ITEMS: 'saiWardrobeItems',
  OUTFIT_SELECTIONS: 'outfitSelections',
  DAILY_LOOKS: 'saiDailyLooks',
  OUTFIT_PREFERENCES: 'saiOutfitPreferences',
  WEEK_PLANS: 'saiWeekPlans',
  PIECE_LIKES: 'saiPieceLikes',
  PIECE_RATINGS: 'saiPieceRatings',
  PIECE_STATS: 'saiPieceStats',
  OUTFIT_LIKES: 'saiOutfitLikes',
  OUTFIT_COMMENTS: 'saiOutfitComments',
  FOLLOWS: 'saiFollows',
  REMIXES: 'saiRemixes',
  NOTIFICATIONS: 'saiNotifications',
  BRAND_SEALS: 'saiBrandSeals',
  BRAND_SEAL_APPLICATIONS: 'saiBrandSealApplications',
  BRAND_FEED_POSTS: 'saiBrandFeedPosts',
  BRAND_FEED_SPOTLIGHTS: 'saiBrandFeedSpotlights',
  SUBSCRIPTIONS: 'saiSubscriptions',
  ART_CELEBRITY_ARENA: 'saiArtCelebrityArena',
  ART_CELEBRITY_TRIBUTES: 'saiArtCelebrityTributes',
} as const;

export const LEGACY_COLLECTIONS = [
  'sai-brands',
  'sai-markets',
  'sai-pieceItems',
  'sai-pipelineJobs',
  'sai-scheme',
  'sai-schemeitem',
  'sai-usercontrol',
  'sai-usersavedschemes',
  'sai-wardrobeItems',
  'outfit_selection_2d',
] as const;
